<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NEWSPAPER [
<!ELEMENT NEWSPAPER (ARTICLE+)>
<!ELEMENT ARTICLE (HEADLINE,BYLINE,LEAD,BODY,NOTES)>
<!ELEMENT HEADLINE (#PCDATA)>
<!ELEMENT BYLINE (#PCDATA)>
<!ELEMENT LEAD (#PCDATA)>
<!ELEMENT BODY (#PCDATA)>
<!ELEMENT NOTES (#PCDATA)>
<!ATTLIST ARTICLE AUTHOR CDATA #REQUIRED>
<!ATTLIST ARTICLE EDITOR CDATA #IMPLIED>
<!ATTLIST ARTICLE DATE CDATA #IMPLIED>
<!ATTLIST ARTICLE EDITION CDATA #IMPLIED> ]>

<NEWSPAPER>
<ARTICLE AUTHOR="Xiang" EDITOR="Paco" DATE="22-02-2000" EDITION="01">
<HEADLINE> GME gana un 20% en undia.</HEADLINE>
<BYLINE></BYLINE>
<LEAD></LEAD>
<BODY>GME</BODY>
<NOTES>Articulo en construccion.</NOTES>
</ARTICLE>
</NEWSPAPER>